### ISSUE TITLE
Missing parts of GPL-3

### ISSUE THREAD

**Issue by rrrlw** [rcarragh/c212#1]
Please fill in lines 196, 197, 212, and 216 in the LICENSE file.

Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/2706).

**Comment by rcarragh** [comment]
I have updated the LICENSE file (see also #3). After "END OF TERMS AND CONDITIONS" I've added 

Year: 2020
COPYRIGHT HOLDER: Raymond Carragher
Contact: rcarragh@gmail.com

**Comment by rrrlw** [comment]
Looks great, thank you!
