### ISSUE TITLE
Dependency versioning

### ISSUE THREAD

**Issue by rrrlw** [rcarragh/c212#2]
Adding version requirements to dependency lists in DESCRIPTION can help improve package robustness (in case older dependency versions break code). Would you be willing to add a version requirement for the `coda` dependency? (e.g. `coda >= 0.19` or whichever min version you choose)

Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/2706).

**Comment by rcarragh** [comment]
I've updated the DESCRIPTION to code (>= 0.19) as you suggest. Older version should be OK but I agree that this is better.

**Comment by rrrlw** [comment]
Looks great, thank you!
