### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by rrrlw** [rcarragh/c212#4]
One of JOSS's submission requirements is the presence of clear community guidelines for potential contributors. Would you be willing to add appropriate guidelines to this repo? (e.g. in `CONTRIBUTING.md` and/or `CODE_OF_CONDUCT.md` files)

If unsure where to start, I think it would be helpful to check out [Contributor Covenant](https://www.contributor-covenant.org).

Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/2706).

**Comment by rcarragh** [comment]
I am happy to do this. 
I have added CODE_OF_CONDUCT.md and CONTRIBUTING.md to the repository.

**Comment by rrrlw** [comment]
Looks great, thank you!
