### ISSUE TITLE
The articles should explain more/correctly about MedDRA and the SOC/PT

### ISSUE THREAD

**Issue by rcarragh** [rcarragh/c212#7]
The articles should explain more/correctly about MedDRA and the SOC/PT in the sentence “A number of methods, which use groupings of adverse events by body-system or System Organ Class” as this is key/central to the methods presented, especially some of the Bayesian approaches.

**Comment by rcarragh** [comment]
I've added in a couple of paragraphs in the Summary section (paragraphs 3, 4 and the start of 5) about medical dictionaries, leading up to the methods.

**Comment by MelvinSMunsaka** [comment]
@rcarragh I have reviewed the revised text and it is acceptable. You can also close this comment.

**Comment by rcarragh** [comment]
@MelvinSMunsaka - thanks
