### ISSUE TITLE
The reference “Fries, M., Kracht, K., & Li, J. (2016). Safety monitoring methodology in the premarketing setting. Proceedings of JSM, 2247–2269. Retrieved from https://ww2.amstat.org/MembersOnly/proceedings/2016/data/assets/pdf/389675.pdf” is incorrect.

### ISSUE THREAD

**Issue by rcarragh** [rcarragh/c212#8]
The reference “Fries, M., Kracht, K., & Li, J. (2016). Safety monitoring methodology in the premarketing setting. Proceedings of JSM, 2247–2269. Retrieved from https://ww2.amstat.org/MembersOnly/proceedings/2016/data/assets/pdf/389675.pdf” is incorrect. It should be “Fries, M., Kracht, K. K., Li, J., Munsaka, M. S., Sanchez-Kam, M., Singh, K. P., Wang, W., Whalen, E., Zhou. K. (2016). Safety Monitoring Methodology in the Premarketing Setting JSM 2016 Proceedings, Biopharmaceutical Section, 2247 - 2269. https://ww2.amstat.org/MembersOnly/proceedings/2016/data/assets/pdf/389675.pdf”

**Comment by rcarragh** [comment]
I've updated the reference to include the complete author list. 
I'm not sure why I had an incomplete list but apologies to those left off the original.

**Comment by MelvinSMunsaka** [comment]
@rcarragh This is OK. You can close this comment.

**Comment by rcarragh** [comment]
@MelvinSMunsaka - great thanks
